// Metadaten & Anleitungen der Trainingsmodi (Deutsch + Englisch). `board` steuert
// das Highlight im erklärenden Dartboard (numbers + ring).

export const TRAINING_MODES = [
  {
    id: 'clock',
    name: 'Around the Clock',
    nameEn: 'Around the Clock',
    short: 'Der Reihe nach 1 → 20 → Bull treffen.',
    shortEn: 'Hit 1 → 20 → Bull in order.',
    category: 'Genauigkeit',
    categoryEn: 'Accuracy',
    difficulty: 'Einfach',
    difficultyEn: 'Easy',
    better: 'low',
    unit: 'Darts',
    unitEn: 'darts',
    rules: [
      'Triff die Felder nacheinander in der Reihenfolge 1, 2, 3 … 20 und zum Schluss das Bull.',
      'Für jeden Wurf tippst du „Treffer" (weiter zum nächsten Feld) oder „Daneben".',
      'Ziel: die komplette Runde mit möglichst wenigen Darts schaffen – dein Bestwert ist die geringste Dartzahl.',
    ],
    rulesEn: [
      'Hit the fields one after another in the order 1, 2, 3 … 20 and finally the Bull.',
      'For each throw tap "Hit" (advance to the next field) or "Miss".',
      'Goal: complete the whole round with as few darts as possible – your best is the lowest dart count.',
    ],
    board: { numbers: [1, 2, 3, 4, 5], ring: 'number' },
  },
  {
    id: 'bob27',
    name: "Bob's 27",
    nameEn: "Bob's 27",
    short: 'Doppel-Training D1 → D20 → Bull, Konto ab 27.',
    shortEn: 'Doubles training D1 → D20 → Bull, starting at 27.',
    category: 'Doppel',
    categoryEn: 'Doubles',
    difficulty: 'Mittel',
    difficultyEn: 'Medium',
    better: 'high',
    unit: 'Punkte',
    unitEn: 'points',
    rules: [
      'Du startest mit 27 Punkten und spielst nacheinander D1, D2, … D20 und das Bullseye.',
      'Pro Doppel wirfst du 3 Darts. Jeder Treffer bringt den doppelten Feldwert (D3 = 6 Punkte).',
      'Triffst du in einer Runde gar nicht, wird der Doppelwert abgezogen. Fällt das Konto unter 0, ist Schluss.',
      'Ziel: möglichst viele Punkte – der Bestwert ist dein höchstes Endergebnis.',
    ],
    rulesEn: [
      'You start with 27 points and play D1, D2, … D20 and the bullseye in turn.',
      'You throw 3 darts per double. Each hit scores double the field value (D3 = 6 points).',
      'If you miss completely in a round, the double value is subtracted. If the balance drops below 0, it ends.',
      'Goal: as many points as possible – your best is your highest final score.',
    ],
    board: { numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], ring: 'double' },
  },
  {
    id: 'countup',
    name: 'Count-up (High-Score)',
    nameEn: 'Count-up (high score)',
    short: 'Feste Rundenzahl, maximale Punkte scoren.',
    shortEn: 'Fixed number of rounds, score as much as possible.',
    category: 'Scoring',
    categoryEn: 'Scoring',
    difficulty: 'Einfach',
    difficultyEn: 'Easy',
    better: 'high',
    unit: 'Punkte',
    unitEn: 'points',
    rules: [
      'Es werden 8 Runden zu je 3 Darts gespielt – ohne Rest, einfach so viel wie möglich scoren.',
      'Trage nach jeder Runde deine Aufnahme-Summe ein.',
      'Der 3-Dart-Ø fließt in deine Trainings-Statistik ein; der Bestwert ist die höchste Gesamtpunktzahl.',
    ],
    rulesEn: [
      '8 rounds of 3 darts are played – no remainder, simply score as much as possible.',
      'Enter your visit total after each round.',
      'The 3-dart average feeds into your training statistics; the best is the highest total score.',
    ],
    board: { numbers: [20, 19, 18], ring: 'triple' },
  },
  {
    id: 'cricket',
    name: 'Cricket (Solo)',
    nameEn: 'Cricket (solo)',
    short: '20–15 und Bull „schließen".',
    shortEn: 'Close 20–15 and the Bull.',
    category: 'Genauigkeit',
    categoryEn: 'Accuracy',
    difficulty: 'Mittel',
    difficultyEn: 'Medium',
    better: 'low',
    unit: 'Darts',
    unitEn: 'darts',
    rules: [
      'Ziele sind 20, 19, 18, 17, 16, 15 und das Bull. Jedes Feld muss dreimal getroffen („geschlossen") werden.',
      'Ein Single zählt 1 Mark, ein Double 2, ein Triple 3.',
      'Tippe das getroffene Feld an (mit Multiplikator) oder „Daneben". Ziel: alle Felder mit möglichst wenigen Darts schließen.',
    ],
    rulesEn: [
      'Targets are 20, 19, 18, 17, 16, 15 and the Bull. Each field must be hit three times ("closed").',
      'A single counts 1 mark, a double 2, a triple 3.',
      'Tap the field you hit (with multiplier) or "Miss". Goal: close all fields with as few darts as possible.',
    ],
    board: { numbers: [15, 16, 17, 18, 19, 20, 25], ring: 'number' },
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    nameEn: 'Shanghai',
    short: 'Je Runde Zielzahl auf Single/Double/Triple.',
    shortEn: 'Each round a target number on single/double/triple.',
    category: 'Genauigkeit',
    categoryEn: 'Accuracy',
    difficulty: 'Mittel',
    difficultyEn: 'Medium',
    better: 'high',
    unit: 'Punkte',
    unitEn: 'points',
    rules: [
      'In Runde 1 zielst du auf die 1, in Runde 2 auf die 2 … bis Runde 7.',
      'Punkte = getroffener Wert (Single/Double/Triple der Zielzahl), summiert über alle Runden.',
      'Triffst du in einer Runde Single, Double UND Triple der Zielzahl → „Shanghai" und sofort gewonnen!',
    ],
    rulesEn: [
      'In round 1 you aim at the 1, in round 2 at the 2 … up to round 7.',
      'Points = value hit (single/double/triple of the target number), summed over all rounds.',
      'If you hit single, double AND triple of the target number in one round → "Shanghai" and instant win!',
    ],
    board: { numbers: [1], ring: 'number' },
  },
  {
    id: 'halveit',
    name: 'Halve-it',
    nameEn: 'Halve-it',
    short: 'Zielvorgaben je Runde – verfehlt = Punkte halbiert.',
    shortEn: 'Targets per round – miss = points halved.',
    category: 'Konstanz',
    categoryEn: 'Consistency',
    difficulty: 'Mittel',
    difficultyEn: 'Medium',
    better: 'high',
    unit: 'Punkte',
    unitEn: 'points',
    rules: [
      'Feste Ziel-Abfolge: 15, 16, beliebiges Double, 17, 18, beliebiges Triple, 19, 20, Bull.',
      'Pro Runde 3 Darts auf das Ziel; die erzielten Punkte werden addiert.',
      'Triffst du das Ziel gar nicht (0 Punkte), wird dein bisheriger Punktestand halbiert. Ziel: möglichst hoher Endstand.',
    ],
    rulesEn: [
      'Fixed target sequence: 15, 16, any double, 17, 18, any triple, 19, 20, Bull.',
      '3 darts per round at the target; the points scored are added up.',
      'If you miss the target entirely (0 points), your current score is halved. Goal: highest possible final score.',
    ],
    board: { numbers: [15, 16, 17, 18, 19, 20, 25], ring: 'number' },
  },
  {
    id: 'checkout',
    name: 'Checkout-Challenge (121)',
    nameEn: 'Checkout challenge (121)',
    short: '121 in 3 Darts auschecken – Finish-Training.',
    shortEn: 'Check out 121 in 3 darts – finishing practice.',
    category: 'Checkout',
    categoryEn: 'Checkout',
    difficulty: 'Schwer',
    difficultyEn: 'Hard',
    better: 'high',
    unit: 'Checkouts',
    unitEn: 'checkouts',
    rules: [
      'Du versuchst 10 Runden lang, 121 in genau 3 Darts auszuchecken (Double-Out).',
      'Nach jedem Versuch wählst du, ob du es geschafft hast (mit wie vielen Darts) oder nicht.',
      'Der Bestwert ist die Anzahl erfolgreicher Checkouts (von 10). Tipp-Route für 121: T20 – T11 – D14.',
    ],
    rulesEn: [
      'For 10 rounds you try to check out 121 in exactly 3 darts (double-out).',
      'After each attempt you choose whether you made it (with how many darts) or not.',
      'The best is the number of successful checkouts (out of 10). Suggested route for 121: T20 – T11 – D14.',
    ],
    board: { numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], ring: 'double' },
  },
  {
    id: 'checkoutdrill',
    name: 'Checkout-Trainer',
    nameEn: 'Checkout trainer',
    short: 'Rest-Stände auschecken – Nur-Doppel & „unter Druck".',
    shortEn: 'Check out finishes – doubles-only & "under pressure".',
    category: 'Checkout',
    categoryEn: 'Checkout',
    difficulty: 'Schwer',
    difficultyEn: 'Hard',
    better: 'high',
    unit: 'Checkouts',
    unitEn: 'checkouts',
    rules: [
      'Du bekommst nacheinander Rest-Stände und versuchst, sie mit max. 3 Darts auf Double-Out zu checken.',
      'Optionen: „Nur Doppel" übt reine Doppel-Rest-Stände (2–40, Bull); „Unter Druck" wiederholt denselben Rest bis zum Treffer.',
      'Pro Versuch tippst du, mit wie vielen Darts es geklappt hat – oder „daneben". Bestwert = erfolgreiche Checkouts.',
    ],
    rulesEn: [
      'You get a series of remaining scores and try to check them out with max. 3 darts (double-out).',
      'Options: "doubles only" drills pure double finishes (2–40, Bull); "under pressure" repeats the same finish until you hit it.',
      'Per attempt you tap how many darts it took – or "missed". Best = successful checkouts.',
    ],
    board: { numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], ring: 'double' },
  },
  {
    id: 'doublesround',
    name: 'Doppel-Rundlauf',
    nameEn: 'Doubles round',
    short: 'D1 → D20 → Bull, Trefferquote je Doppel.',
    shortEn: 'D1 → D20 → Bull, hit rate per double.',
    category: 'Doppel',
    categoryEn: 'Doubles',
    difficulty: 'Mittel',
    difficultyEn: 'Medium',
    better: 'high',
    unit: 'Treffer',
    unitEn: 'hits',
    rules: [
      'Du spielst nacheinander D1, D2 … D20 und das Bullseye – je 3 Darts.',
      'Tippe pro Feld, wie viele der 3 Darts getroffen haben (0–3).',
      'Bestwert = Gesamttreffer (von 63). Die Quoten fließen in dein Doppel-/Checkout-Profil ein.',
    ],
    rulesEn: [
      'Play D1, D2 … D20 and the bullseye in turn – 3 darts each.',
      'Tap how many of the 3 darts hit each field (0–3).',
      'Best = total hits (out of 63). The rates feed your doubles/checkout profile.',
    ],
    board: { numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], ring: 'double' },
  },
  {
    id: 'triplesround',
    name: 'Triple-Rundlauf',
    nameEn: 'Triples round',
    short: 'T1 → T20, Trefferquote je Triple.',
    shortEn: 'T1 → T20, hit rate per triple.',
    category: 'Scoring',
    categoryEn: 'Scoring',
    difficulty: 'Schwer',
    difficultyEn: 'Hard',
    better: 'high',
    unit: 'Treffer',
    unitEn: 'hits',
    rules: [
      'Du spielst nacheinander T1, T2 … T20 – je 3 Darts.',
      'Tippe pro Feld, wie viele der 3 Darts das Triple getroffen haben (0–3).',
      'Bestwert = Gesamttreffer (von 60). Die Quoten fließen in dein Triple-/Checkout-Profil ein.',
    ],
    rulesEn: [
      'Play T1, T2 … T20 in turn – 3 darts each.',
      'Tap how many of the 3 darts hit the triple per field (0–3).',
      'Best = total hits (out of 60). The rates feed your triples/checkout profile.',
    ],
    board: { numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], ring: 'triple' },
  },
  {
    id: 'bulltrain',
    name: 'Bull-Training',
    nameEn: 'Bull training',
    short: '10 Runden aufs Bull – Trefferquote 25/Bull.',
    shortEn: '10 rounds at the bull – 25/bull hit rate.',
    category: 'Genauigkeit',
    categoryEn: 'Accuracy',
    difficulty: 'Mittel',
    difficultyEn: 'Medium',
    better: 'high',
    unit: 'Treffer',
    unitEn: 'hits',
    rules: [
      'Du wirfst 10 Runden zu je 3 Darts auf das Bull (25/50).',
      'Tippe pro Runde, wie viele der 3 Darts im Bull-Bereich waren (0–3).',
      'Bestwert = Gesamttreffer (von 30). Die Bull-Quote fließt in dein Checkout-Profil ein.',
    ],
    rulesEn: [
      'Throw 10 rounds of 3 darts at the bull (25/50).',
      'Tap how many of the 3 darts landed in the bull area per round (0–3).',
      'Best = total hits (out of 30). The bull rate feeds your checkout profile.',
    ],
    board: { numbers: [25], ring: 'bull' },
  },
  {
    id: 'drill20',
    name: 'Scoring-Drill: T20',
    nameEn: 'Scoring drill: T20',
    short: '10 Runden auf die Triple 20 – Trefferquote.',
    shortEn: '10 rounds at treble 20 – hit rate.',
    category: 'Scoring',
    categoryEn: 'Scoring',
    difficulty: 'Schwer',
    difficultyEn: 'Hard',
    better: 'high',
    unit: 'Treffer',
    unitEn: 'hits',
    rules: [
      'Du wirfst 10 Runden zu je 3 Darts auf die Triple 20.',
      'Tippe pro Runde, wie viele der 3 Darts die T20 getroffen haben (0–3).',
      'Bestwert = Gesamttreffer (von 30).',
    ],
    rulesEn: [
      'Throw 10 rounds of 3 darts at treble 20.',
      'Tap how many of the 3 darts hit T20 per round (0–3).',
      'Best = total hits (out of 30).',
    ],
    board: { numbers: [20], ring: 'triple' },
  },
  {
    id: 'drill19',
    name: 'Scoring-Drill: T19',
    nameEn: 'Scoring drill: T19',
    short: '10 Runden auf die Triple 19 – Trefferquote.',
    shortEn: '10 rounds at treble 19 – hit rate.',
    category: 'Scoring',
    categoryEn: 'Scoring',
    difficulty: 'Schwer',
    difficultyEn: 'Hard',
    better: 'high',
    unit: 'Treffer',
    unitEn: 'hits',
    rules: [
      'Du wirfst 10 Runden zu je 3 Darts auf die Triple 19.',
      'Tippe pro Runde, wie viele der 3 Darts die T19 getroffen haben (0–3).',
      'Bestwert = Gesamttreffer (von 30).',
    ],
    rulesEn: [
      'Throw 10 rounds of 3 darts at treble 19.',
      'Tap how many of the 3 darts hit T19 per round (0–3).',
      'Best = total hits (out of 30).',
    ],
    board: { numbers: [19], ring: 'triple' },
  },
  {
    id: 'drill100',
    name: 'Scoring-Drill: 100+',
    nameEn: 'Scoring drill: 100+',
    short: '10 Aufnahmen – zähle die 100+-Aufnahmen.',
    shortEn: '10 visits – count the 100+ visits.',
    category: 'Scoring',
    categoryEn: 'Scoring',
    difficulty: 'Mittel',
    difficultyEn: 'Medium',
    better: 'high',
    unit: 'Aufnahmen',
    unitEn: 'visits',
    rules: [
      'Du spielst 10 Aufnahmen zu je 3 Darts und trägst die Aufnahme-Summe ein.',
      'Gezählt wird, wie viele Aufnahmen 100 oder mehr Punkte hatten.',
      'Bestwert = Anzahl der 100+-Aufnahmen (von 10). Der Ø fließt in die Scoring-Statistik ein.',
    ],
    rulesEn: [
      'Play 10 visits of 3 darts and enter each visit total.',
      'Counted is how many visits scored 100 or more.',
      'Best = number of 100+ visits (out of 10). The average feeds the scoring statistics.',
    ],
    board: { numbers: [20, 19, 18], ring: 'triple' },
  },
  {
    id: 'drill140',
    name: 'Scoring-Drill: 140+',
    nameEn: 'Scoring drill: 140+',
    short: '10 Aufnahmen – zähle die 140+-Aufnahmen.',
    shortEn: '10 visits – count the 140+ visits.',
    category: 'Scoring',
    categoryEn: 'Scoring',
    difficulty: 'Schwer',
    difficultyEn: 'Hard',
    better: 'high',
    unit: 'Aufnahmen',
    unitEn: 'visits',
    rules: [
      'Du spielst 10 Aufnahmen zu je 3 Darts und trägst die Aufnahme-Summe ein.',
      'Gezählt wird, wie viele Aufnahmen 140 oder mehr Punkte hatten.',
      'Bestwert = Anzahl der 140+-Aufnahmen (von 10). Der Ø fließt in die Scoring-Statistik ein.',
    ],
    rulesEn: [
      'Play 10 visits of 3 darts and enter each visit total.',
      'Counted is how many visits scored 140 or more.',
      'Best = number of 140+ visits (out of 10). The average feeds the scoring statistics.',
    ],
    board: { numbers: [20, 19, 18], ring: 'triple' },
  },
];

export const MODE_BY_ID = Object.fromEntries(TRAINING_MODES.map((m) => [m.id, m]));

// Liefert die sprachabhängigen Felder eines Modus (lang = 'de' | 'en').
export function localizeMode(m, lang) {
  if (!m) return m;
  const en = lang === 'en';
  return {
    ...m,
    name: en ? m.nameEn || m.name : m.name,
    short: en ? m.shortEn || m.short : m.short,
    category: en ? m.categoryEn || m.category : m.category,
    difficulty: en ? m.difficultyEn || m.difficulty : m.difficulty,
    unit: en ? m.unitEn || m.unit : m.unit,
    rules: en ? m.rulesEn || m.rules : m.rules,
  };
}
